apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-mysql
  template:
    metadata:
      labels:
        app: drupal-mysql
    spec:
      volumes:
        - name: drupal-mysql-volume
          persistentVolumeClaim:
            claimName: drupal-mysql-pvc
      containers:
        - name: mysql-container
          image: mysql:5.7
          volumeMounts:
            - name: drupal-mysql-volume
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-root-password
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-url
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-user-password
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-mysql-user-password
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  type: ClusterIP
  selector:
    app: drupal-mysql
  ports:
    - port: 3306
