apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-root-password
stringData:
  password: asDF@#45@#$
---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-url
stringData:
  database: drupal_web
---
apiVersion: v1
kind: Secret
metadata:
  name: drupal-mysql-user-password
stringData:
  username: drupal_user
  password: Aas324%#$53sdFAS
