apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iron-namespace-datacenter
  name: iron-gallery-deployment-datacenter
  labels:
    run: iron-gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      run: iron-gallery
  template:
    metadata:
      labels:
        run: iron-gallery
    spec:
      containers:
        - name: iron-gallery-container-datacenter
          image: kodekloud/irongallery:2.0
          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/data
            - name: images
              mountPath: /usr/share/nginx/html/uploads
      volumes:
        - name: config
          emptyDir: {}
        - name: images
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: iron-namespace-datacenter
  name: iron-gallery-service-datacenter
spec:
  type: NodePort
  selector:
    run: iron-gallery
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32678
