apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
stringData:
  password: R00t
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
stringData:
  username: kodekloud_sam
  password: GyQkFRVNr3
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
stringData:
  database: kodekloud_db6
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
stringData:
  host: 127.0.0.1
